[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
serde = { version = "1.0.208", features = ["derive"]}
serde_json = "1.0.125"
typetag = "0.2.18"
websocket = "0.27.1"
